Repository web-servers/narayana-tomcat, pull requests merged in 2018-09, with the labels that each got.

#14 Adds check for DB's ability to execute test SELECT 1; statement also …
  .gitignore
  tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/AbstractCase.java
  tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/BaseITCase.java
Labels: bug

#12 remove shade and clean dependencies.
  tomcat-jta/pom.xml
Labels: enhancement

#10 JWS-1124 Update to add the transaction synchronization registry
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java
  tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/AbstractCase.java
Labels: enhancement

#2 pom.xml formatting, spaces instead of irregularly used tabs
  pom.xml
  tomcat-jta/pom.xml
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/NarayanaJtaServletContextListener.java
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/PoolingDataSource.java
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionManagerFactory.java
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionSynchronizationRegistryFactory.java
  tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java
  tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestTransactionalDataSourceFactory.java
  tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/app/TestExecutor.java
  tomcat-jta/src/test/resources/arquillian.xml
  tools/pom.xml
  tools/src/main/java/io/narayana/db/H2Allocator.java
Labels: trivial

#19 Adds checkstyle plugin configuration and Wildfly rules with supress c…
  checkstyle-suppressions.xml
  pom.xml
Labels: enhancement

#21 update to add the jacoco
  pom.xml
Labels: enhancement

#23 upgrade jacoco to 0.8.2 and remove the comments
  pom.xml
Labels: enhancement

#22 arquillian.container.tomcat to 1.1.Final
  pom.xml
Labels: enhancement

#24 Formatting See http://bit.ly/2MTnhFd
  pom.xml
Labels: trivial
